name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish Blazor Project
        run: dotnet publish Source/Beans/Beans.csproj -c Release -o release

      - name: Change base-tag in index.html
        run: sed -i 's|<base href="/"|<base href="/beans/"|g' release/wwwroot/index.html

      - name: Verify base href was updated
        run: grep '<base' release/wwwroot/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/wwwroot

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4